#!/usr/bin/env node
/**
 * The Session Watchdog build — one source tree, three variants.
 *
 *   build/chrome   service worker (classic bundle)  -> Chrome + Opera
 *   build/firefox  event page (classic bundle)      -> Firefox
 *   build/test     chrome + harness origin          -> E2E in the replay
 *   dist/          packed zips of chrome + firefox
 *
 * The source is ES modules (repo convention: node --test unit tests);
 * the bundles are single-file classic scripts so the same code runs in
 * a non-module Chrome service worker and a Firefox event page without
 * any namespace polyfill (src/api.js wraps chrome.*, which all three
 * browsers implement).
 *
 * No dependencies: the bundler is a tiny deterministic concatenator
 * that understands exactly the import/export shapes this codebase uses.
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, copyFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");

const HARNESS_ORIGIN = "http://127.0.0.1:8099";

/* ─────────────────── the micro-bundler ─────────────────── */

/**
 * Bundle an ES-module entry into one classic script.
 * Understands: import { a, b } from "./rel.js"  |  import * as ns from ...
 *              export const/function NAME ... (top-level declarations)
 *              export { a, b }
 * Constraint-checked (fails the build on anything else) — this is a
 * build for a frozen small codebase, not a general transpiler.
 */
function bundle(entryRel) {
  const modules = [];
  const seen = new Map();

  function load(rel) {
    if (seen.has(rel)) return seen.get(rel);
    const path = join(SRC, rel);
    const raw = readFileSync(path, "utf8");

    // collect imports
    const imports = [];
    const importRe = /^import\s+(?:\{([^}]*)\}|(\*\s+as\s+[\w$]+))\s+from\s*["']([^"']+)["'];?\s*$/gm;
    let m;
    while ((m = importRe.exec(raw))) {
      const names = m[1]
        ? m[1].split(",").map((s) => s.trim()).filter(Boolean)
        : [m[2].trim()];
      imports.push({ spec: m[3], names });
    }
    let body = raw.replace(importRe, "");

    // exports: named declaration forms -> strip the keyword, keep names
    const exported = new Set();
    body = body.replace(
      /^export\s+(const|let|var|function|class)\s+([\w$]+)/gm,
      (_all, kind, name) => {
        exported.add(name);
        return `${kind} ${name}`;
      }
    );
    // re-export lists: export { a, b } (from local scope)
    body = body.replace(/^export\s*\{([^}]*)\};?\s*$/gm, (_all, list) => {
      for (const n of list.split(",").map((s) => s.trim()).filter(Boolean)) {
        exported.add(n);
      }
      return "";
    });
    // bare `export default` is not used in this codebase — fail on it
    if (/^\s*export\s+default/m.test(body)) {
      throw new Error(`export default is unsupported: ${rel}`);
    }

    const mod = { rel, imports, body, exported: [...exported] };
    modules.push(mod);
    seen.set(rel, mod);
    return mod;
  }

  const entry = load(entryRel);

  // resolve dependency order (deps first; simple DFS)
  const order = [];
  const visited = new Set();
  function resolveSpec(fromRel, spec) {
    if (spec.startsWith(".")) {
      return join(dirname(fromRel), spec).replace(/^\/+/, "");
    }
    return spec.replace(/^\/+/, "");
  }
  function visit(mod) {
    if (visited.has(mod.rel)) return;
    visited.add(mod.rel);
    for (const imp of mod.imports) {
      visit(load(resolveSpec(mod.rel, imp.spec)));
    }
    order.push(mod);
  }
  visit(entry);

  // namespace prefix per module (identifiers stay readable in stacks)
  const nsName = (rel) => "sw_" + rel.replace(/[^\w]/g, "_");

  const parts = [];
  parts.push("/* generated by build.mjs — do not edit */");
  parts.push("(function () {\n\"use strict\";\n");

  // hoisted module namespaces
  for (const mod of order) parts.push(`var ${nsName(mod.rel)} = {};`);

  for (const mod of order) {
    // bind this module's imported names FIRST (its deps are already
    // evaluated — deps precede dependents in `order`)
    for (const imp of mod.imports) {
      const target = nsName(resolveSpec(mod.rel, imp.spec));
      for (const name of imp.names) {
        const nsImport = /^\*\s+as\s+/.test(name);
        const alias = name.replace(/^\*\s+as\s+/, "");
        parts.push(nsImport ? `var ${alias} = ${target};` : `var ${alias} = ${target}.${name};`);
      }
    }
    parts.push(`\n/* ── ${mod.rel} ── */`);
    // module body inside a function returning its exports
    parts.push(`${nsName(mod.rel)} = (function () {\n${mod.body}\nreturn {`);
    if (mod.exported.length > 0) {
      parts.push(mod.exported.map((n) => `  ${n}: typeof ${n} !== "undefined" ? ${n} : undefined,`).join("\n"));
    }
    parts.push("};\n})();");
  }

  parts.push("\n})();");
  return parts.join("\n");
}

/* ─────────────────── variants ─────────────────── */

function manifestFor(variant, version) {
  const base = {
    manifest_version: 3,
    name: "Session Watchdog",
    version,
    description:
      "Watches chat.z.ai sessions and relaunches them when they freeze, return, die or stop mid-task. Chrome, Opera and Firefox.",
    action: {
      default_title: "Session Watchdog",
      default_popup: "popup/popup.html",
      default_icon: {
        "16": "icons/icon16.png",
        "32": "icons/icon32.png",
        "48": "icons/icon48.png",
        "128": "icons/icon128.png",
      },
    },
    icons: {
      "16": "icons/icon16.png",
      "32": "icons/icon32.png",
      "48": "icons/icon48.png",
      "128": "icons/icon128.png",
    },
    // v1.1: clipboardWrite = the diagnostics copy button; offscreen (chrome
    // only) = the looping alarm sound; notifications = the Ubuntu desktop
    // alert surface + its Silence button
    permissions: ["storage", "tabs", "alarms", "notifications", "clipboardWrite"],
    content_scripts: [
      {
        matches: ["https://chat.z.ai/*"],
        js: ["content.js"],
        run_at: "document_idle",
      },
    ],
  };
  if (variant === "chrome") {
    base.background = { service_worker: "background.js" };
    base.permissions.push("offscreen");
    // the alert endpoints (Brevo email + ntfy push) + optional webhooks
    base.host_permissions = ["https://chat.z.ai/*", "https://api.brevo.com/*", "https://ntfy.sh/*"];
    base.optional_host_permissions = ["http://*/*", "https://*/*"];
  } else if (variant === "firefox") {
    base.background = { scripts: ["background.js"] };
    // Firefox has no chrome.offscreen — the alarm degrades to a visible
    // alarm tab (src/offscreen/alarm.html) with the same sound + STOP.
    base.host_permissions = ["https://chat.z.ai/*", "https://api.brevo.com/*", "https://ntfy.sh/*"];
    base.browser_specific_settings = {
      gecko: { id: "session-watchdog@payswap.org", strict_min_version: "109.0" },
    };
  } else if (variant === "test") {
    base.name = "Session Watchdog (test)";
    base.background = { service_worker: "background.js" };
    base.permissions.push("offscreen");
    // BOTH origins: the harness for the E2E matrix, the REAL provider for
    // the live-surface validation pass. Which origin gets WATCHED is a
    // runtime setting (providerOrigin) — the matches only decide where
    // the sensor can run.
    base.host_permissions = ["https://chat.z.ai/*", "https://api.brevo.com/*", "https://ntfy.sh/*", `${HARNESS_ORIGIN}/*`];
    base.optional_host_permissions = ["http://*/*", "https://*/*"];
    base.content_scripts[0].matches = ["https://chat.z.ai/*", `${HARNESS_ORIGIN}/*`];
  } else {
    throw new Error(`unknown variant: ${variant}`);
  }
  return base;
}

/* ─────────────────── run ─────────────────── */

const VERSION = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).version;

function buildVariant(variant) {
  const out = join(ROOT, "build", variant);
  rmSync(out, { recursive: true, force: true });
  mkdirSync(join(out, "popup"), { recursive: true });
  mkdirSync(join(out, "icons"), { recursive: true });
  mkdirSync(join(out, "offscreen"), { recursive: true });

  writeFileSync(join(out, "manifest.json"), JSON.stringify(manifestFor(variant, VERSION), null, 2));
  // the build marker (v1.3): the bundled worker reports the version of the
  // SCRIPT it executes — a stale cached worker keeps answering the old one,
  // which is exactly how the E2E detects it (swBuild in sw-get-state)
  writeFileSync(join(out, "background.js"), bundle("background/background.js").replaceAll("__SW_BUILD__", VERSION));
  writeFileSync(join(out, "content.js"), bundle("content/content.js"));
  for (const f of ["popup.html", "popup.css", "popup.js"]) {
    copyFileSync(join(SRC, "popup", f), join(out, "popup", f));
  }
  // the alarm page: the chrome.offscreen document AND the Firefox alarm tab
  for (const f of ["alarm.html", "alarm.js"]) {
    copyFileSync(join(SRC, "offscreen", f), join(out, "offscreen", f));
  }
  for (const f of ["icon16.png", "icon32.png", "icon48.png", "icon128.png"]) {
    const icon = join(ROOT, "icons", f);
    if (!existsSync(icon)) throw new Error(`missing icon: ${icon}`);
    copyFileSync(icon, join(out, "icons", f));
  }
  console.log(`built build/${variant} (${VERSION})`);
}

for (const v of ["chrome", "firefox", "test"]) buildVariant(v);

// dist zips
const dist = join(ROOT, "dist");
rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
for (const v of ["chrome", "firefox"]) {
  execSync(`cd build/${v} && zip -qr ../../dist/session-watchdog-${v}.zip .`, { cwd: ROOT, stdio: "inherit" });
  console.log(`packed dist/session-watchdog-${v}.zip`);
}
console.log("done");
